name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, "*"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name:  Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Run Python unit tests
      run: python3 -u -m pytest tests/tests.py
